import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'react-material-symbols/rounded'; 
import {
  QueryClient,
  QueryClientProvider,
  useQuery,
} from '@tanstack/react-query'
import QueryProvider from "./providers/QueryProvider";
import RecoilContextProvider from "./providers/RecoilProvider";




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        {/* <QueryClientProvider client={queryClient}> */}
        <QueryProvider>
        <RecoilContextProvider>
          {children}
        </RecoilContextProvider>
        </QueryProvider>

        {/* </QueryClientProvider> */}
        </body>
    </html>
  );
}
